import { useEffect, useState, type ReactNode } from 'react';
import { Bell, Menu, Search, CheckCircle2, Moon, Sun } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { useLocation, useNavigate } from 'react-router-dom';
import PortalSidebar from './PortalSidebar';
import { PortalProvider } from './PortalContext';
import type { Role } from '../../config/navigation';
import { roles } from '../../config/navigation';
import { deanLogout } from '../../services/deanAuth';
import { api } from '../../services/api';
import { getTheme, setTheme, subscribeToTheme, type Theme } from '../../lib/theme';
export default function PortalShell({role,title,children}:{role:Role;title:string;children:ReactNode}){const location=useLocation();const navigate=useNavigate();const [mobileOpen,setMobileOpen]=useState(false);const [theme,setThemeState]=useState<Theme>(()=>getTheme());const dark=theme==='dark';const [query,setQuery]=useState('');const [toast,setToast]=useState('');useEffect(()=>subscribeToTheme(setThemeState),[]);useEffect(()=>{let active=true;api.auth.me().then(()=>{if(active){}}).catch(()=>{if(active){deanLogout();navigate('/login',{replace:true})}});return()=>{active=false}},[navigate,location.pathname]);useEffect(()=>{window.scrollTo({top:0,left:0,behavior:'auto'});setMobileOpen(false);setQuery('')},[location.pathname]);const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2800)};const roleInfo=roles.find(r=>r.id===role)!;return <PortalProvider value={{role,query,notify,openCreate:()=>{}}}><div className={`portal-shell role-${role}`}><PortalSidebar role={role} mobileOpen={mobileOpen} onClose={()=>setMobileOpen(false)}/>{mobileOpen&&<button className="portal-backdrop" aria-label="Close navigation" onClick={()=>setMobileOpen(false)}/>}<main className="portal-main"><header className="portal-top"><div className="portal-top-left"><button className="portal-menu" onClick={()=>setMobileOpen(true)}><Menu size={18}/></button><div><span>SGGSIE&T / Dean Admin</span><h1>{title}</h1></div></div><div className="portal-actions"><div className="portal-search"><Search size={15}/><input placeholder="Search content, data or media…" value={query} onChange={e=>setQuery(e.target.value)}/></div><button aria-label={dark?'Switch to light theme':'Switch to dark theme'} onClick={()=>setTheme(dark?'light':'dark')}><span className="portal-theme-icon">{dark?<Sun size={16}/>:<Moon size={16}/>}</span></button><button aria-label="Notifications"><Bell size={16}/></button><div className="avatar">D</div></div></header>{children}</main><AnimatePresence>{toast&&<motion.div className="toast" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:12}}><CheckCircle2 size={16}/>{toast}</motion.div>}</AnimatePresence></div></PortalProvider>}
